# version visible in AppVeyor dashboard only, not correlated with github
version: "v0.1.{build}"
platform: x86

init:
  - git config --global core.autocrlf input

build:
  verbosity: minimal

environment:
  QTDIR: C:\Qt\5.5\mingw492_32
  MINGW: C:\Qt\Tools\mingw492_32
  TARGET: serial-ninja

configuration: Release

install:
  # add Qt, MinGW and 7z to the PATH
  - set PATH=%PATH%;%QTDIR%\bin;%MINGW%\bin
  - set PATH=%PATH%;"C:\Program Files\7-Zip"

before_build:
  - qmake serial-ninja.pro
  # generate name for releases
  - ps: >-
      if($env:APPVEYOR_REPO_TAG -eq 'true') {
        # tag build: concat executable name with tagname
        $env:RELEASE = $env:TARGET + ".win-" + $env:APPVEYOR_REPO_TAG_NAME
      } else {
        # commit build: concat executable name with 'latest'
        $env:RELEASE = $env:TARGET + ".win-latest"
      }
  - ps: $env:ZIP_RELEASE = $env:RELEASE + ".zip"

build_script:
  - mingw32-make -j8
  - windeployqt %APPVEYOR_BUILD_FOLDER%\bin\serial-ninja.exe
  # add missing libwinpthread-1.dll
  - copy /Y %QTDIR%\bin\libwinpthread-1.dll %APPVEYOR_BUILD_FOLDER%\bin

after_build:
  - rename %APPVEYOR_BUILD_FOLDER%\bin %RELEASE% 
  - 7z a %ZIP_RELEASE% %RELEASE%

artifacts:
  - path: $(ZIP_RELEASE)
    name: ZipRelease

deploy:
  # Deploy to GitHub Releases only for tag builds
  - provider: GitHub
    artifact: ZipRelease
    auth_token:
      secure: DP+lbxV/P0SXFccQVIJe0u9Nni6jRs9xxx4JW6Mp9z4DWZIoYZSYnGCCDw2q37Et
    draft: true
    skip_tags: true
    on:
      branch: master
      appveyor_repo_tag: true       # deploy on tag push only

  # Deploy to 'latest' GitHub Releases for every push
# commented the 'latest' release because of the naming problem :
# github won't accept multiple  releases with same name under same tag (latest)
# solution to implement : 
#      # when and if artifact has been created successfully,
#      # remove previous $env:ZIP_RELEASE from github (on latest tag)
# there is MAYBE a way to do this directly on github, with a webhook, though
# i'm not sure about that
#   
#  - provider: GitHub
#    artifact: ZipRelease
#    auth_token:
#      secure: DP+lbxV/P0SXFccQVIJe0u9Nni6jRs9xxx4JW6Mp9z4DWZIoYZSYnGCCDw2q37Et
#    prerelease: true
#     release: latest
#    description: "Automatic build of latest master branch."
#    on:
#      branch: master
